Squashed commit of the following:
commit 526853c3e58433a28626fa592c7681a7f86dcf04
Author: Ethan Davidson <31261035+EthanThatOneKid@users.noreply.github.com>
Date:   Wed Nov 26 01:10:13 2025 -0800

    Add JSDoc comments

commit b09837d666546c8ea299a3459d936807ec82324b
Author: Ethan Davidson <31261035+EthanThatOneKid@users.noreply.github.com>
Date:   Wed Nov 26 01:04:45 2025 -0800

    Set up `@comunica/query-sparql-rdfjs-lite`

commit 5f26ab668b7c56e295f9dec47eb821c034142cbd
Author: Ethan Davidson <31261035+EthanThatOneKid@users.noreply.github.com>
Date:   Wed Nov 26 00:16:36 2025 -0800

    wip implement Comunica executeSparql

    Encountering an error:

    ```
    error: Error: Cannot find module './property-param '
    Require stack:
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\shaclc-write\1.5.0\dist\ShaclcGenerator.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\shaclc-write\1.5.0\dist\index.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\@comunica\actor-rdf-serialize-shaclc\4.5.0\lib\ActorRdfSerializeShaclc.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\@comunica\actor-rdf-serialize-shaclc\4.5.0\lib\index.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\@comunica\query-sparql-rdfjs\4.5.0\engine-default.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\@comunica\query-sparql-rdfjs\4.5.0\lib\QueryEngine.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\@comunica\query-sparql-rdfjs\4.5.0\lib\index.js
    - C:\Users\ethan\AppData\Local\deno\npm\registry.npmjs.org\@comunica\query-sparql-rdfjs\4.5.0\lib\index.js
        at Module._resolveFilename (node:module:633:15)
        at Module._load (node:module:496:27)
        at Module.require (node:module:694:19)
        at require (node:module:828:16)
        at file:///C:/Users/ethan/AppData/Local/deno/npm/registry.npmjs.org/shaclc-write/1.5.0/dist/ShaclcGenerator.js:27:42
        at Object.<anonymous> (file:///C:/Users/ethan/AppData/Local/deno/npm/registry.npmjs.org/shaclc-write/1.5.0/dist/ShaclcGenerator.js:766:3)
        at Module._compile (node:module:757:34)
        at loadMaybeCjs (node:module:782:10)
        at Object.Module._extensions..js (node:module:767:12)
        at Module.load (node:module:675:32)
    ```